### ISSUE TITLE
如何不生成getter/setter方法

### ISSUE THREAD

**Issue by jc0803kevin** [supergaga/generator#1]
现在这个还是会生成getter/setter方法

增加了
modelGetterMethodGenerated return false
modelSetterMethodGenerated return false
还是不生效

**Comment by supergaga** [comment]
你是直接在插件里面用的 这个吗 ？
`      
       <dependency>
            <groupId>com.github.supergaga</groupId>
            <artifactId>generator</artifactId>
            <version>1.0.0</version>
        </dependency>
`

**Comment by jc0803kevin** [comment]
来的最新代码，然后改了一个版本号再引用的

**Comment by supergaga** [comment]
配置贴出来看下

**Comment by jc0803kevin** [comment]
添加了一个继承关系
public abstract class EmptyCommentGenerator extends PluginAdapter implements CommentGenerator

重写以下两个方法
@Override
    public boolean modelGetterMethodGenerated(Method method, TopLevelClass topLevelClass, IntrospectedColumn introspectedColumn, IntrospectedTable introspectedTable, ModelClassType modelClassType) {

        return false;
    }

    @Override
    public boolean modelSetterMethodGenerated(Method method, TopLevelClass topLevelClass, IntrospectedColumn introspectedColumn, IntrospectedTable introspectedTable, ModelClassType modelClassType) {
        return false;
    }

其他的没有变

**Comment by jc0803kevin** [comment]
能加一个微信么，jc0803Kevin

**Comment by supergaga** [comment]
实现的方式还是略有不同的，你加的`PluginAdapter ` 是通过插件做的，我写的这个是通过注解拼上去的

**Comment by 13265377744** [comment]
这个问题解决了吗？请问

**Comment by jc0803kevin** [comment]
@12602037115 解决了，

**Comment by jc0803kevin** [comment]
@12602037115 参考：https://github.com/jc0803kevin/mybatis-generator-lombok-plugin
